server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.194.28:3306/chubby_plan?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Aa@123456
    initialSize: 20
    minIdle: 20
    maxActive: 200
    minEvictableIdleTimeMillis: 300000


file:
  resource:
    innerPath: D://resource
    outerPath: D://resource