spring:
  application:
    name: chubby-plan
  profiles:
    active: pro
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB